### ISSUE TITLE
Move .gitignore from node_modules to root

### ISSUE THREAD

**Issue by senovsky** [djwester/api-testing-foundations#5]
Hi, I believe that you may have mistakenly placed `.gitignore` into the `node_modules` folder instead of the root of your repo. Currently, after cloning and running `npm install`, all the node modules are labeled as untracked by git instead of being ignored.

**Comment by djwester** [comment]
Thanks for pointing this out! Not sure how that happened, but I've fixed it in this PR:  https://github.com/djwester/api-testing-foundations/pull/6
